name: Deploy Documentation

on:
  push:
    branches: [ main ]  # Change this to your main branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # Specify the Python version you need

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
        python -m pip list

    - name: Build Documentation
      run: |
        cd doc
        sphinx-build -b html source build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/build  # Path to your built documentation
